apiVersion: openchoreo.dev/v1alpha1
kind: Component
metadata:
  name: analytics-service
  namespace: default
spec:
  owner:
    projectName: url-shortener

  componentType:
    kind: ClusterComponentType
    name: deployment/service
  autoDeploy: true

  parameters:
    exposed: true
    replicas: 1
    port: 8081
    resources:
      requests:
        cpu: "100m"
        memory: "256Mi"
      limits:
        cpu: "500m"
        memory: "512Mi"

---
apiVersion: openchoreo.dev/v1alpha1
kind: Workload
metadata:
  name: analytics-service
  namespace: default
spec:
  owner:
    componentName: analytics-service
    projectName: url-shortener
  endpoints:
    http:
      type: HTTP
      port: 8081
  dependencies:
    endpoints:
      - project: url-shortener
        component: postgres
        name: tcp
        visibility: project
        envBindings:
          address: POSTGRES_ADDR
      - project: url-shortener
        component: redis
        name: tcp
        visibility: project
        envBindings:
          address: REDIS_ADDR
  container:
    image: rashadxyz/snip-analytics-service:v0.2.5
    env:
      - key: PORT
        value: "8081"
      - key: POSTGRES_DSN
        value: "postgres://postgres:postgres@postgres:5432/urlshortener?sslmode=disable"
      - key: REDIS_ADDR
        value: "redis:6379"
      - key: OTEL_ENABLED
        value: "true"
      - key: OTEL_EXPORTER_ENDPOINT
        value: "http://opentelemetry-collector.openchoreo-observability-plane.svc.cluster.local:4318"
