apiVersion: openchoreo.dev/v1alpha1
kind: Component
metadata:
  name: frontend
  namespace: default
spec:
  owner:
    projectName: url-shortener

  componentType:
    kind: ClusterComponentType
    name: deployment/web-application
  autoDeploy: true

  parameters:
    replicas: 1
    port: 3000
    resources:
      requests:
        cpu: "100m"
        memory: "256Mi"
      limits:
        cpu: "500m"
        memory: "512Mi"

---
apiVersion: openchoreo.dev/v1alpha1
kind: Workload
metadata:
  name: frontend
  namespace: default
spec:
  owner:
    componentName: frontend
    projectName: url-shortener
  endpoints:
    http:
      type: HTTP
      port: 3000
      visibility: [external]
  dependencies:
    endpoints:
      - project: url-shortener
        component: api-service
        name: http
        visibility: project
        envBindings:
          address: API_SERVICE_ADDR
      - project: url-shortener
        component: analytics-service
        name: http
        visibility: project
        envBindings:
          address: ANALYTICS_SERVICE_ADDR
  container:
    image: rashadxyz/snip-frontend:v0.2.5
    env:
      - key: PORT
        value: "3000"
      - key: API_SERVICE_URL
        value: "http://api-service:8080"
      - key: ANALYTICS_SERVICE_URL
        value: "http://analytics-service:8081"
      - key: OTEL_ENABLED
        value: "true"
      - key: OTEL_EXPORTER_ENDPOINT
        value: "http://opentelemetry-collector.openchoreo-observability-plane.svc.cluster.local:4318"
