apiVersion: openchoreo.dev/v1alpha1
kind: Component
metadata:
  name: frontend
  namespace: default
spec:
  owner:
    projectName: url-shortener

  componentType: deployment/web-application
  autoDeploy: true

  parameters:
    replicas: 1
    port: 3000
    resources:
      requests:
        cpu: "100m"
        memory: "256Mi"
      limits:
        cpu: "500m"
        memory: "512Mi"

---
apiVersion: openchoreo.dev/v1alpha1
kind: Workload
metadata:
  name: frontend
  namespace: default
spec:
  owner:
    componentName: frontend
    projectName: url-shortener
  containers:
    main:
      image: rashadxyz/snip-frontend:v0.1.0
      env:
        - key: PORT
          value: "3000"
        - key: API_SERVICE_URL
          value: "http://api-service:80"
        - key: ANALYTICS_SERVICE_URL
          value: "http://analytics-service:80"
        - key: OTEL_ENABLED
          value: "true"
        - key: OTEL_EXPORTER_ENDPOINT
          value: "http://opentelemetry-collector.openchoreo-observability-plane.svc.cluster.local:4318"
