apiVersion: openchoreo.dev/v1alpha1
kind: Component
metadata:
  name: redis
  namespace: default
spec:
  owner:
    projectName: url-shortener

  componentType:
    kind: ClusterComponentType
    name: deployment/service
  autoDeploy: true

---
apiVersion: openchoreo.dev/v1alpha1
kind: Workload
metadata:
  name: redis
  namespace: default
spec:
  owner:
    componentName: redis
    projectName: url-shortener
  endpoints:
    tcp:
      type: TCP
      port: 6379
  container:
    image: redis:7-alpine
