apiVersion: openchoreo.dev/v1alpha1
kind: Project
metadata:
  annotations:
    openchoreo.dev/description: URL Shortener Demo — shorten URLs, track clicks
    openchoreo.dev/display-name: Snip URL Shortener
  labels:
    openchoreo.dev/name: snip
  name: snip
  namespace: default
spec:
  deploymentPipelineRef: default
