---
# Misconfigure the api-service Postgres DSN
apiVersion: openchoreo.dev/v1alpha1
kind: ReleaseBinding
metadata:
  name: api-service-development
  namespace: default
spec:
  owner:
    projectName: url-shortener
    componentName: api-service
  environment: development
  componentTypeEnvOverrides:
    configurations.env:
      POSTGRES_DSN: "postgres://postgres:postgres@bad-host:5432/urlshortener?sslmode=disable"
