---
# Misconfigure the api-service Postgres DSN and lower memory limits to trigger memory alert
apiVersion: openchoreo.dev/v1alpha1
kind: ReleaseBinding
metadata:
  name: api-service-development
  namespace: default
spec:
  owner:
    projectName: url-shortener
    componentName: api-service
  environment: development
  workloadOverrides:
    container:
      env:
        - key: POSTGRES_DSN
          value: "postgres://postgres:postgres@postgresss:5432/urlshortener?sslmode=disable"
  componentTypeEnvOverrides:
    resources:
      requests:
        memory: "40Mi"
      limits:
        memory: "55Mi"
  traitOverrides:
    api-service-high-memory-alert:
      enabled: true
      enableAiRootCauseAnalysis: true
      notificationChannel: "webhook-notification-channel-development"
