apiVersion: openchoreo.dev/v1alpha1
kind: Component
metadata:
  name: analytics-service
spec:
  owner:
    projectName: url-shortener

  componentType:
    kind: ClusterComponentType
    name: deployment/service
  autoDeploy: true

  workflow:
    name: docker

    parameters:
      scope:
        projectName: "url-shortener"
        componentName: "analytics-service"
      repository:
        url: "https://github.com/rashadism/snip-url-shortener"
        revision:
          branch: "main"
        appPath: "/analytics-service"
      docker:
        context: "/analytics-service"
        filePath: "/analytics-service/Dockerfile"

---
apiVersion: openchoreo.dev/v1alpha1
kind: WorkflowRun
metadata:
  name: analytics-service-build-01
  labels:
    openchoreo.dev/project: "url-shortener"
    openchoreo.dev/component: "analytics-service"
spec:
  workflow:
    name: docker

    parameters:
      scope:
        projectName: "url-shortener"
        componentName: "analytics-service"
      repository:
        url: "https://github.com/rashadism/snip-url-shortener"
        revision:
          branch: "main"
        appPath: "/analytics-service"
      docker:
        context: "/analytics-service"
        filePath: "/analytics-service/Dockerfile"
