apiVersion: openchoreo.dev/v1alpha1
kind: Component
metadata:
  name: postgres
spec:
  owner:
    projectName: url-shortener

  componentType:
    kind: ComponentType
    name: deployment/service
  autoDeploy: true

  workflow:
    name: docker

    parameters:
      scope:
        projectName: "url-shortener"
        componentName: "postgres"
      repository:
        url: "https://github.com/rashadism/snip-url-shortener"
        revision:
          branch: "main"
        appPath: "/db"
      docker:
        context: "/db"
        filePath: "/db/Dockerfile"

---
apiVersion: openchoreo.dev/v1alpha1
kind: WorkflowRun
metadata:
  name: postgres-build-01
  labels:
    openchoreo.dev/project: "url-shortener"
    openchoreo.dev/component: "postgres"
spec:
  workflow:
    name: docker

    parameters:
      scope:
        projectName: "url-shortener"
        componentName: "postgres"
      repository:
        url: "https://github.com/rashadism/snip-url-shortener"
        revision:
          branch: "main"
        appPath: "/db"
      docker:
        context: "/db"
        filePath: "/db/Dockerfile"
