apiVersion: openchoreo.dev/v1alpha1
kind: Component
metadata:
  name: redis
  namespace: default
spec:
  owner:
    projectName: url-shortener

  componentType: deployment/service
  autoDeploy: true

  workflow:
    name: docker

    systemParameters:
      repository:
        url: "https://github.com/rashadism/snip-url-shortener"
        revision:
          branch: "main"
        appPath: "/redis"

    parameters:
      docker:
        context: "/redis"
        filePath: "/redis/Dockerfile"

  parameters:
    replicas: 1
    port: 6379
    resources:
      requests:
        cpu: "50m"
        memory: "128Mi"
      limits:
        cpu: "200m"
        memory: "256Mi"

---
apiVersion: openchoreo.dev/v1alpha1
kind: ComponentWorkflowRun
metadata:
  name: redis-build-01
spec:
  owner:
    projectName: url-shortener
    componentName: redis

  workflow:
    name: docker

    systemParameters:
      repository:
        url: "https://github.com/rashadism/snip-url-shortener"
        revision:
          branch: "main"
        appPath: "/redis"

    parameters:
      docker:
        context: "/redis"
        filePath: "/redis/Dockerfile"
